<?php


$jobssetsqlarr['uid']=$companyinfo['uid'];
$jobssetsqlarr['companyname']=$companyinfo['companyname'];
$jobssetsqlarr['company_id']=$companyinfo['id'];
$jobssetsqlarr['company_addtime']=$companyinfo['addtime'];
$jobssetsqlarr['jobs_name']=trim($_POST['jobs_name']);
if (empty($jobssetsqlarr['jobs_name']))  exit("职位名称丢失");
if (ck_jobs_name($jobssetsqlarr['jobs_name'],$jobssetsqlarr['uid'])) exit("职位名称有重复");
$jobssetsqlarr['contents']=html2text($_POST['jobs_contents']);
$nature=locoyspider_jobs_nature(trim($_POST['jobs_nature']));
$jobssetsqlarr['nature']=$nature['id'];
$jobssetsqlarr['nature_cn']=$nature['cn'];
$sex=locoyspider_jobs_sex(trim($_POST['jobs_sex']));
$jobssetsqlarr['sex']=$sex['id'];
$jobssetsqlarr['sex_cn']=$sex['cn'];
//年龄要求
$jobssetsqlarr['age']=trim($_POST['jobs_age']);
$jobssetsqlarr['amount']=locoyspider_jobs_amount(trim($_POST['jobs_amount']));
$jobs_category=trim($_POST['jobs_category'])?trim($_POST['jobs_category']):$jobssetsqlarr['jobs_name'];
$category=locoyspider_jobs_category($jobs_category);//$_POST['jobs_category']
//一级
$jobssetsqlarr['topclass']=$category['topclass'];
$jobssetsqlarr['category']=$category['category'];
$jobssetsqlarr['subclass']=$category['subclass'];
$jobssetsqlarr['category_cn']=$category['category_cn'];
$jobssetsqlarr['trade']=$companyinfo['trade'];
$jobssetsqlarr['trade_cn']=$companyinfo['trade_cn'];
$district=locoyspider_jobs_district(trim($_POST['jobs_district']));
$jobssetsqlarr['scale']=$companyinfo['scale'];
$jobssetsqlarr['scale_cn']=$companyinfo['scale_cn'];
$jobssetsqlarr['district']=$district['district'];
$jobssetsqlarr['sdistrict']=$district['sdistrict'];
$jobssetsqlarr['district_cn']=$district['district_cn'];
//街道id 和 街道
$jobssetsqlarr['street']=$companyinfo['street'];
$jobssetsqlarr['street_cn']=$companyinfo['street_cn'];
$education=locoyspider_jobs_education(trim($_POST['jobs_education']));
$jobssetsqlarr['education']=$education['id'];
$jobssetsqlarr['education_cn']=$education['cn'];
$experience=get_experience(trim($_POST['jobs_experience']));
$jobssetsqlarr['experience']=$experience['id'];
$jobssetsqlarr['experience_cn']=$experience['cn'];
$wage=locoyspider_jobs_wage(trim($_POST['jobs_wage']));
$jobssetsqlarr['wage']=$wage['id'];
$jobssetsqlarr['wage_cn']=$wage['cn'];
$jobssetsqlarr['addtime']=time();
$jobssetsqlarr['deadline']=locoyspider_jobs_deadline();
$jobssetsqlarr['refreshtime']=time();
$jobssetsqlarr['key']=$jobssetsqlarr['jobs_name'].$companyinfo['companyname'].$jobssetsqlarr['category_cn'].$jobssetsqlarr['district_cn'].$jobssetsqlarr['contents'];
require_once(QISHI_ROOT_PATH.'include/splitword.class.php');
$sp = new SPWord();
$jobssetsqlarr['key']="{$jobssetsqlarr['jobs_name']} {$companyinfo['companyname']} ".$sp->extracttag($jobssetsqlarr['key']);
$jobssetsqlarr['key']=$sp->pad($jobssetsqlarr['key']);
$jobssetsqlarr['audit']=$locoyspider['jobs_audit'];
$jobssetsqlarr['display']=$locoyspider['jobs_display'];
$jobssetsqlarr['robot']=1;
$pid=inserttable(table('jobs'),$jobssetsqlarr,true);
if (!$pid) exit("添加招聘信息失败");
//职位联系方式
$setsqlarr_contact['contact']=trim($_POST['contact']);
//QQ
$setsqlarr_contact['qq']=trim($_POST['qq']);
$setsqlarr_contact['telephone']=trim($_POST['telephone']);
$setsqlarr_contact['address']=trim($_POST['address']);
$setsqlarr_contact['email']=check_email(trim($_POST['email']));
//3.4新增字段,3.5也有
$setsqlarr_contact['contact_show']=1;
$setsqlarr_contact['telephone_show']=1;
$setsqlarr_contact['email_show']=1;
$setsqlarr_contact['address_show']=1;
$setsqlarr_contact['qq_show']=1;

$setsqlarr_contact['notify']=$locoyspider['jobs_notify'];
$setsqlarr_contact['pid']=$pid;
if (!inserttable(table('jobs_contact'),$setsqlarr_contact)) exit("添加招聘联系方式失败");
//------
$searchtab['id']=$pid;
$searchtab['uid']=$jobssetsqlarr['uid'];
$searchtab['recommend']=$jobssetsqlarr['recommend'];
$searchtab['emergency']=$jobssetsqlarr['emergency'];
$searchtab['nature']=$jobssetsqlarr['nature'];
$searchtab['sex']=$jobssetsqlarr['sex'];
$searchtab['topclass']=$jobssetsqlarr['topclass'];
$searchtab['category']=$jobssetsqlarr['category'];
$searchtab['subclass']=$jobssetsqlarr['subclass'];
$searchtab['trade']=$jobssetsqlarr['trade'];
$searchtab['district']=$jobssetsqlarr['district'];
$searchtab['sdistrict']=$jobssetsqlarr['sdistrict'];
$searchtab['street']=$companyinfo['street'];
$searchtab['education']=$jobssetsqlarr['education'];
$searchtab['experience']=$jobssetsqlarr['experience'];
$searchtab['wage']=$jobssetsqlarr['wage'];
$searchtab['refreshtime']=$jobssetsqlarr['refreshtime'];
$searchtab['scale']=$jobssetsqlarr['scale'];
//
inserttable(table('jobs_search_wage'),$searchtab);
inserttable(table('jobs_search_scale'),$searchtab);
inserttable(table('jobs_search_rtime'),$searchtab);
//
$searchtab['stick']=$jobssetsqlarr['stick'];
inserttable(table('jobs_search_stickrtime'),$searchtab);
unset($searchtab['stick']);
//
$searchtab['click']=$jobssetsqlarr['click'];
inserttable(table('jobs_search_hot'),$searchtab);
unset($searchtab['click']);
//
$searchtab['likekey']=$jobssetsqlarr['jobs_name'].','.$jobssetsqlarr['companyname'];
$searchtab['key']=$jobssetsqlarr['key'];
inserttable(table('jobs_search_key'),$searchtab);
$tagsql['tag1']=$tagsql['tag2']=$tagsql['tag3']=$tagsql['tag4']=$tagsql['tag5']=0;
$tagsql['id']=$pid;
$tagsql['uid']=$jobssetsqlarr['uid'];
$tagsql['topclass']=$jobssetsqlarr['topclass'];
$tagsql['category']=$jobssetsqlarr['category'];
$tagsql['subclass']=$jobssetsqlarr['subclass'];
$tagsql['district']=$jobssetsqlarr['district'];
$tagsql['sdistrict']=$jobssetsqlarr['sdistrict'];
inserttable(table('jobs_search_tag'),$tagsql);
require_once(ADMIN_ROOT_PATH.'include/admin_company_fun.php');
distribution_jobs($pid);
exit("添加成功");

?>